### ISSUE TITLE
New Methods

### ISSUE THREAD

**Issue by techopswhiz** [taskbit/HiRezApi#1]
Can you please update to include the latest methods or instruct me on how to do that?

**Comment by taskbit** [comment]
I added the code for the REST client [generator](https://github.com/taskbit/HiRezApi/tree/swagger-gen) which I used to automatically generate the C# API methods & models.
An alternative would be that you manually add the methods & models for the new API operations [here ](https://github.com/taskbit/HiRezApi/tree/master/src/Generated/Paladins)

Feel free to submit a pull request, I'm currently not able to provide an update.
